prevent accidental contrast degradations via test
This commit introduces a test that asserts that the minimum WCAG
contrast ratio of a style is specified in
./test/contrast/min_contrasts.json.

When a contrast is decreased the test fails with, e.g:

  Error: minimum contrast decreased for style default.css (2.4 < 3.4)
  if this is intentional please run tools/updateContrasts.js -f

When you improve a minimum contrast the test fails with:

  Error: congrats, you improved the minimum contrast of default.css, please run tools/updateContrasts.js

In both cases running the script as instructed updates the JSON file,
making the test pass.