fix(parser) Resolve issue with missing TS property (#3225)
Using `highlightElement` with version 10.7.2 causes the following
TypeScript build error: "error TS2339: Property 'highlightElement' does
not exist on type 'HLJSApi'."