fix(parser) Resolve issue with missing TS property
Using `highlightElement` with version 10.7.2 causes the following
TypeScript build error: "error TS2339: Property 'highlightElement' does
not exist on type 'HLJSApi'."